spring:
    profiles:
        active: prod
    application:
        name: foo
    datasource:
        url: jdbc:h2:file:./DB/testdb
        username: sa
        password: '1234'
        driverClassName: org.h2.Driver
    jpa:
        database-platform: org.hibernate.dialect.H2Dialect
    h2:
        console:
            enabled: true

customQuery: select prop_key, prop_value from MyProperties where profile = ?